server:
  port: 8011

spring:
  application:
    name: product-service  #应用名称，本名称会被nacos作为服务名称
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
        # service: 同spring.application.name
        # group: