server:
  port: 8010

spring:
  application:
    name: order-service  #应用名称，本名称会被nacos作为服务名称
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
        # service: 同spring.application.name
        # group:
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
      datasource:
        flow-rule:
          server-addr: 127.0.0.1:8848
          username: nacos
          password: nacos
          dataId: order-sentinel-flow-rule
          rule-type: flow
logging:
  level:
    com.soopen.feign: debug

feign:
  client:
    config:
      order-service: #服务名
        connectTimeout: 5000   #连接超时时间，默认2S
        readTimeout: 10000     #请求处理超时间，默认5s
        requestInterceptors[0]: #配置拦截器
          com.soopen.interceptor.FeignAuthReuestInterceptor
  sentinel:
    enabled: true  #整合sentinel
